### ISSUE TITLE
Example needs rename to include lib name

### ISSUE THREAD

**Issue by kattni** [adafruit/Adafruit_CircuitPython_BitmapSaver#4]
Example `screenshot_simpletest.py` should be named `bitmapsaver_screenshot_simpletest.py` to fit with CircuitPython library standards and clarify which library it is associated with in the example bundle.

The lines including this file name in the `docs/examples.rst` file must also be updated to reflect the name change, e.g.:
```
.. literalinclude:: ../examples/current_file_name.py
    :caption: examples/current_file_name.py
    :linenos:
```
would be updated to:
```
.. literalinclude:: ../examples/current_file_name_changed.py
    :caption: examples/current_file_name_changed.py
    :linenos:
```

**Comment by dherrada** [comment]
Solved by #6
